services:
  mongodb:
    image: mongo:latest
    container_name: click-n-build-mongodb-service
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodata:/data/db
      - ./db/logs:/var/log/mongodb
      - ./db/mongod.conf:/etc/mongod.conf
      - ./db/init.d:/docker-entrypoint-initdb.d:ro
  mongo-express:
    image: mongo-express:latest
    container_name: click-n-build-mongo-express-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/
  nuxt:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
      args:
        PORT: 8000
    image: click-n-build-nuxt:latest
    container_name: click-n-build-nuxt-service
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./node_modules:/nuxt/node_modules
    depends_on:
      - mongodb
  nginx:
    image: nginx:latest
    hostname: clicknbuild.com
    container_name: click-n-build-web-service
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nuxt

volumes:
  mongodata:
