FROM node:20.5.1-bookworm as base

ENV NODE_ENV=development

ARG PORT=8000

WORKDIR /nuxt

# Build

FROM base as build

COPY --link . .
COPY --link package*.json .
RUN npm install

# Run

FROM base

COPY --from=build /nuxt .

ENV PORT=${PORT}

CMD [ "npm", "run", "dev" ]